style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/parisni/dfzf
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - chore
        - ci
        - license
        - doc
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Maintenance
      ci: CI/CD
      license: Licensing
      doc: Documentation
  header:
    pattern: "^(\\w+)(\\(([^)]+)\\))?: (.+)"
    pattern_maps:
    - Type
    - Scope
    - Scope
    - Subject
  notes:
    keywords:
      - BREAKING CHANGE

